---
- name: remove packages
  apt: name={{ purge_packages }} state=absent

- name: install additional packages
  apt: name={{ install_packages }} state=latest

- name: allow everything and enable ufw
  ufw: state=enabled policy=allow

- name: deny 3gpi interface
  ufw: rule=deny direction=in interface={{ item }}
  with_items:
    - ppp0

- name: purge unused packages
  include_role:
    name: common
    tasks_from: autopurge

- name: upgrade packages
  apt: upgrade=dist

- name: purge unused packages
  include_role:
    name: common
    tasks_from: autopurge

- name: copy config files
  copy: src=./ dest=/ owner=root group=root mode=0644

- name: configure avahi-daemon
  lineinfile: dest=/etc/avahi/avahi-daemon.conf
              backrefs=yes
              regexp={{ item.regexp }}
              line={{ item.line }}
              backup=yes
  with_items:
    - { regexp: '^#deny-interfaces=(.*)', line: 'deny-interfaces=' }
    - { regexp: '^deny-interfaces=(.*)', line: '#deny-interfaces=\1' }
    - { regexp: '^#deny-interfaces=(.*)', line: 'deny-interfaces=\1' }
    - { regexp: '^deny-interfaces=((?!.*ppp0).*[^,])\n', line: 'deny-interfaces=\1,' }
    - { regexp: '^deny-interfaces=((?!.*ppp0).*)', line: 'deny-interfaces=\1ppp0' }

