---
- name: configure keyboard
  lineinfile: dest=/etc/default/keyboard
              regexp={{ item.regexp }}
              line={{ item.line }}
              backup=yes
  with_items:
  - { regexp: '^XKBLAYOUT=', line: 'XKBLAYOUT="jp"' }

- name: configure rng-tools
  lineinfile: dest=/etc/default/rng-tools
              regexp={{ item.regexp }}
              insertafter={{ item.insertafter }}
              line={{ item.line }}
              backup=yes
  with_items:
  - { regexp: '^#HRNGDEVICE=/dev/hwrng', line: 'HRNGDEVICE=/dev/hwrng', insertafter: '^#HRNGDEVICE=' }

- name: configure system.conf
  block:
    - lineinfile: dest=/etc/systemd/system.conf
                  backrefs=yes
                  regexp={{ item.regexp }}
                  line={{ item.line }}
                  backup=yes
      with_items:
        - { regexp: '^ShutdownWatchdogSec=(.*)', line: '#ShutdownWatchdogSec=\1' }
        - { regexp: '^#ShutdownWatchdogSec=', line: 'ShutdownWatchdogSec=10min' }
        - { regexp: '^RuntimeWatchdogSec=(.*)', line: '#RuntimeWatchdogSec=\1' }
        - { regexp: '^#RuntimeWatchdogSec=', line: 'RuntimeWatchdogSec=10' }
    - lineinfile: dest=/etc/systemd/system.conf
                  regexp={{ item.regexp }}
                  insertafter={{ item.insertafter }}
                  line={{ item.line }}
                  backup=yes
      with_items:
        - { regexp: '^ShutdownWatchdogSec=.*', line: 'ShutdownWatchdogSec=10min', insertafter: '\[Manager\]' }
        - { regexp: '^RuntimeWatchdogSec=.*', line: 'RuntimeWatchdogSec=10', insertafter: '\[Manager\]' }

- name: disable periodic apt
  lineinfile: dest=/etc/apt/apt.conf.d/10periodic
              regexp='^APT::Periodic::Enable '
              line='APT::Periodic::Enable "0";'
              backup=yes
              create=yes

- name: set timezone
  command: timedatectl set-timezone Asia/Tokyo

- name: update timezone
  command: dpkg-reconfigure -f noninteractive tzdata

- name: restart keyboard-setup service 
  service: name=keyboard-setup state=restarted

- name: restart console-setup service
  service: name=console-setup state=restarted

#- name: change wifi country
#  command: raspi-config nonint do_wifi_country JP

#- name: change boot behaviour
#  command: raspi-config nonint do_boot_behaviour B1

#- name: disable timesync service
#  command: timedatectl set-ntp false

